### ISSUE TITLE
any plans on supporting v16 of node

### ISSUE THREAD

**Issue by tharun-allu** [Sleavely/docker-node-awscli#3]
Hi, 
Are there any plans on supporting version 16 of node ?

**Comment by Sleavely** [comment]
Long term? Absolutely. Since it is not yet one of the [supported AWS Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) I haven't been in a rush to set up a build process for v16. If you think it would be useful I could set it up sometime this week?

**Comment by tharun-allu** [comment]
Thanks. That would be great. AWS CDK newer versions need node 16 so it will definitely help those people who use it.

**Comment by Sleavely** [comment]
[sleavely/node-awscli:16.x](https://hub.docker.com/layers/sleavely/node-awscli/16.x/images/sha256-e9cc557432f4ff2aa34a912aff6b0ab7a6f23aacc9f29000d063e8ae5579fa5e?context=explore) is now on Docker Hub 👍 

I've created a [v16 branch](https://github.com/Sleavely/docker-node-awscli/tree/v16) in this repo and [updated](https://github.com/Sleavely/commit-on-release/commit/3bf4f3cd64d82b1d7f17cf76f71875286a375786) `commit-on-release` to create commits for `node:16` so it should be automatically up-to-date from now on.
