### ISSUE TITLE
Support for Node 20

### ISSUE THREAD

**Issue by anthonyk89** [Sleavely/docker-node-awscli#5]
Any chance support for Node 20 be added?

**Comment by Sleavely** [comment]
Absolutely, I just haven't gotten around to it yet because I'm still on 16 and 18 😅 . I'll set it up now.

**Comment by Sleavely** [comment]
`sleavely/node-awscli:20.x` is live as of [bf7bf58](https://github.com/Sleavely/docker-node-awscli/commit/bf7bf586a368add06e9741362992fa88d4e3aa7f). Enjoy!
