### ISSUE TITLE
Node version 21 Image

### ISSUE THREAD

**Issue by aanu1994** [Sleavely/docker-node-awscli#7]
Hi Sleavely, could you create and publish a version of the docker image to docker hub using node version 21 please.

**Comment by Sleavely** [comment]
Hi aanu1994,

Normally I only create tags for the supported Lambda runtimes which are linked to LTS releases. I see that Node 22 was released recently (2024-04-24), would that work for you?

**Comment by yq314** [comment]
Hi @Sleavely could you publish Node 22 version? Thanks

**Comment by yq314** [comment]
Made a PR for v22 https://github.com/Sleavely/docker-node-awscli/pull/8

**Comment by Sleavely** [comment]
`22.x` is now published. Thanks for the assist, @yq314 :)
